name: ${name}
version: ${version}
main: ${mainClass}
authors: [mbaxter, ${author}]
website: ${url}
description: ${description}
softdepend: [Essentials,dynmap,JSONAPI,bPermissions,Spout,GeoIPTools,TagAPI,ProtocolLib,Vault, PlaceholderAPI]

dev-url: http://dev.bukkit.org/server-mods/vanish/
api-version: 1.13

commands:
  vanish:
    description: poof
    usage: /vanish
    aliases: [v,np,nf,ni,nc,nh]

permissions:
  vanish.vanish:
    default: op
    description: |
      Allows player to vanish. 
      REALLY should give players with this access to vanish.see
    children:
      vanish.vanish.on: true
      vanish.vanish.off: true
  vanish.vanish.on:
    default: op
    description: Can set state to vanished
  vanish.vanish.off:
    default: op
    description: Can set state to unvanished from vanished
  vanish.see:
    default: op
    description: Allows player to see vanished players
  vanish.statusupdates:
    default: op
    description: Informed about players changing status
  vanish.list:
    default: op
    description: Acquire a list of vanished users
  vanish.nopickup:
    default: op
    description: If true player can pick up items when vanished
  vanish.nofollow:
    default: op
    description: If true mobs do not follow player when vanished
  vanish.notrample:
    default: op
    description: If true player does not trample crops
  vanish.nointeract:
    default: op
    description: If true player cannot press buttons, break or place blocks, open doors, activate pressure pads etc
  vanish.nochat:
    default: op
    description: No chatting while vanished
  vanish.nohunger:
    default: op
    description: Nom nom nom. If true, doesn't lose food level when vanished
  vanish.preventincomingdamage:
    default: op
    description: Prevent being harmed by things around you while vanished
  vanish.preventoutgoingdamage:
    default: op
    description: Prevent accidentally hurting stuff while vanished
  vanish.preventdamage:
    default: op
    description: Prevent damage both ways
    children:
      vanish.preventoutgoingdamage: true
      vanish.preventincomingdamage: true
  vanish.joinwithoutannounce:
    default: op
    description: Join without announcing it
  vanish.joinvanished:
    default: op
    description: Join vanished
  vanish.silentjoin:
    default: op
    description: Join silently. Announce on toggling vanish off
    children:
      vanish.joinwithoutannounce: true
      vanish.joinvanished: true
  vanish.silentquit:
    default: op
    description: ALWAYS quit silently. 
  vanish.silentchests:
    default: op
    description: Allows user to read chests silently while vanished
  vanish.toggle.silentchests:
    default: op
    description: Toggle ability to read chests silently
  vanish.toggle.see:
    default: op
    description: Toggle seeing other vanished players
  vanish.toggle.nopickup:
    default: op
    description: Toggle pickup ability
  vanish.toggle.nofollow:
    default: op
    description: Toggle mob aggro
  vanish.toggle.nointeract:
    default: op
    description: Toggle interaction ability (doors, pressurepads, buttons, breaking or placing blocks, etc)
  vanish.toggle.nochat:
    default: op
    description: Toggle ability to chat
  vanish.toggle.nohunger:
    default: op
    description: Toggle ability to not lose hunger
  vanish.toggle.damageout:
    default: op
    description: Toggle outgoing damage
  vanish.toggle.damagein:
    default: op
    description: Toggle incoming damage
  vanish.toggle.damage:
    default: op
    description: Toggle both damage in and out
    children:
      vanish.toggle.damageout: true
      vanish.toggle.damagein: true
  vanish.toggle.all:
    default: op
    description: Allows user to toggle all their settings ingame
    children:
      vanish.toggle.silentchests: true
      vanish.toggle.see: true
      vanish.toggle.nopickup: true
      vanish.toggle.nofollow: true
      vanish.toggle.damage: true
      vanish.toggle.nointeract: true
      vanish.toggle.nochat: true
      vanish.toggle.nohunger: true
  vanish.fakeannounce:
    default: op
    description: Fake joining/leaving
  vanish.adminalerts:
    default: op
    description: Receive alerts about updates and such
  vanish.permtest.self:
    default: true
    description: If PermTest is enabled, be able to use it on yourself
  vanish.permtest.other:
    default: op
    description: If PermTest is enabled, be able to use it on others
  vanish.permtest.all:
    default: op
    description: If PermTest is enabled, be able to use on self and others
    children:
      vanish.permtest.self: true
      vanish.permtest.other: true
  vanish.hooks.dynmap.alwayshidden:
    default: op
    description: Always hide from dynmap
  vanish.hooks.essentials.hide:
    default: op
    description: Hide user in Essentials
  vanish.spout.status:
    default: op
    description: See a status bar if vanished in spoutcraft
  vanish.reload:
    default: op
    description: Reloads some VNP systems
  vanish.effects.smoke:
    default: op
    description: Creates smoke effect when vanishing and re-appearing
  vanish.effects.explode:
    default: op
    description: Creates explosion effect when vanishing and re-appearing
  vanish.effects.lightning:
    default: op
    description: Creates a lightning barrage around a player when vanishing and re-appearing
  vanish.effects.flames:
    default: op
    description: Creates a mob spawner flames effect around a player when vanishing and re-appearing
  vanish.effects.bats:
    default: op
    description: Creates a swarm of bats around a player when vanishing and re-appearing
  vanish.effects.toggle.smoke:
    default: op
    description: Toggle smoke on vanish toggle
  vanish.effects.toggle.explode:
    default: op
    description: Toggle explode on vanish toggle
  vanish.effects.toggle.lightning:
    default: op
    description: Toggle lightning on vanish toggle
  vanish.effects.toggle.flames:
    default: op
    description: Toggle flames on vanish toggle
  vanish.effects.toggle.bats:
    default: op
    description: Toggle bats on vanish toggle
  vanish.effects.toggle.all:
    default: op
    description: Toggle all vanish toggle effects
    children:
      vanish.effects.toggle.smoke: true
      vanish.effects.toggle.explode: true
      vanish.effects.toggle.lightning: true
      vanish.effects.toggle.flames: true
      vanish.effects.toggle.bats: true
  vanish.op:
    default: op
    description: The permission nodes given to ops
    children:
      vanish.reload: true
      vanish.adminalerts: true
      vanish.permtest.all: true
      vanish.see: true
      vanish.vanish: true
      vanish.statusupdates: true
      vanish.list: true
  vanish.standard:
    default: op
    description: Can vanish, see vanished, no pickup when vanished
    children:
      vanish.see: true
      vanish.vanish: true
      vanish.list: true
      vanish.nopickup: true
      vanish.nofollow: true
      vanish.notrample: true
      vanish.nointeract: true
      vanish.nohunger: true
      vanish.fakeannounce: true
      vanish.preventdamage: true
      vanish.statusupdates: true
      vanish.adminalerts: true
      vanish.silentchests: true
  vanish.*:
    default: op    
    description: Oh god everything.
    children:
      vanish.standard: true
      vanish.nochat: true
      vanish.silentjoin: true
      vanish.silentquit: true
      vanish.toggle.all: true
      vanish.hooks.dynmap.alwayshidden: true
      vanish.hooks.essentials.hide: true
      vanish.permtest.all: true
      vanish.spout.status: true
      vanish.reload: true
      vanish.effects.smoke: true
      vanish.effects.explode: true
      vanish.effects.lightning: true
      vanish.effects.flames: true
      vanish.effects.bats: true
      vanish.effects.toggle.all: true